from enum import Enum


class DraftStatus(str, Enum):
    WAITING_FOR_CAPTAIN2 = 'WAITING_FOR_CAPTAIN2'
    WAIT_EVENS_ODDS_CHOICE_CAP1 = 'WAIT_EVENS_ODDS_CHOICE_CAP1'
    WAIT_EVENS_ODDS_CHOICE_CAP2 = 'WAIT_EVENS_ODDS_CHOICE_CAP2'
    CAPTAIN1_SELECTING = 'CAPTAIN1_SELECTING'
    CAPTAIN2_SELECTING = 'CAPTAIN2_SELECTING'
    FINISHED = 'FINISHED'
