from enum import Enum


class MoveType(str, Enum):
    SELECT_PLAYER = 'SELECT_PLAYER'
    CREATE_SESSION = 'CREATE_SESSION'
    JOIN_SESSION = 'JOIN_SESSION'
    CAPTAIN_JOIN_SESSION = 'CAPTAIN_JOIN_SESSION'
    EVENS_ODDS_CHOICE_CAP1 = 'EVENS_ODDS_CHOICE_CAP1'
    EVENS_ODDS_CHOICE_CAP2 = 'EVENS_ODDS_CHOICE_CAP2'
